### ISSUE TITLE
ST7735 Menu

### ISSUE THREAD

**Issue by ConnalM** [KrisKasprzak/Adafruit_ST7735_Menu#1]
Hi,

I've been using your ILI9341 menu code and it looks great! My next mini project uses an ST7735, so I was happy that I found that you had created the code for it (as I had started down the route of adapting yout ILI9341 code). However, I see that you have removed a bit of the functionality for the ST7735 and I haven't, as yet, managed to get an example of the ST7735 working.

I wondered if you would be able to quickly put something together or point out what the differences are that I need to be aware of? 

Also, what was the reason for removing the functionality? I really like the icons, for example.

Many thanks for your continued support. All the other menus I have seen pale in comparison...

Connal

**Comment by KrisKasprzak** [comment]
Yea, long story but I typically only use ST7735 displays with underpowered MCU such as NANO's. Unfortunately they did not have enough RAM for complex menu code, so I had to strip this lib down to bare min. I don't recall why the code foot print was still too big even if methods were not called. I ran out of time messing with it as I rarely use these displays.
I could mess with the lib and see if I can get the cool  stuff to also work with small memory MCU's
Thanks,
Kris ***@***.***
 

    On Tuesday, March 14, 2023 at 07:48:39 AM CDT, ConnalM ***@***.***> wrote:  
 
 


Hi,

I've been using your ILI9341 menu code and it looks great! My next mini project uses an ST7735, so I was happy that I found that you had created the code for it (as I had started down the route of adapting yout ILI9341 code). However, I see that you have removed a bit of the functionality for the ST7735 and I haven't, as yet, managed to get an example of the ST7735 working.

I wondered if you would be able to quickly put something together or point out what the differences are that I need to be aware of?

Also, what was the reason for removing the functionality? I really like the icons, for example.

Many thanks for your continued support. All the other menus I have seen pale in comparison...

Connal

**Comment by ConnalM** [comment]
That would be great! I'm using an esp32 wroom, so I imagine that you wouldn't need to cut the ili9341 esp32 version down but whatever you can manage would be a great help.

Thanks 

Connal

**Comment by ConnalM** [comment]
[ST7735_Menu_Connal.zip](https://github.com/KrisKasprzak/Adafruit_ST7735_Menu/files/10983670/ST7735_Menu_Connal.zip)

Hi,

I've had a go at making the changes to the sketch for ST7735 (160 x 128 version) and I've changed the cpp and h files too, to put back in the functionality of the original ILI9341 menu. It's not very pretty at the moment, as I haven't put in smaller images, so it is all NI but at least it works. It may be of use to you.

Connal

**Comment by KrisKasprzak** [comment]
It's easier than that...This lib is an exact copy of the Adafruit_ILI9341_Menu, but renamed object types.
Updated lib with an updated example for the ESP32
https://github.com/KrisKasprzak/Adafruit_ST7735_Menu


Thanks,
Kris ***@***.***
 

    On Wednesday, March 15, 2023 at 02:02:07 PM CDT, ConnalM ***@***.***> wrote:  
 
 


ST7735_Menu_Connal.zip

Hi,

I've had a go at making the changes to the sketch for ST7735 (160 x 128 version) and I've changed the cpp and h files too, to put back in the functionality of the original ILI9341 menu. It's not very pretty at the moment, as I haven't put in smaller images, so it is all NI but at least it works. It may be of use to you.

Connal

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
GitHub - KrisKasprzak/Adafruit_ST7735_Menu

Contribute to KrisKasprzak/Adafruit_ST7735_Menu development by creating an account on GitHub.
 |

 |

 |

**Comment by KrisKasprzak** [comment]
Updated lib with an updated example for the ESP32

Please pull the new code and replace existing.

**Comment by ConnalM** [comment]
Hi,

I don't know how you did that but it looks great! 

One minor change I did make, though was on line 817:

EditMenu ColorMenu(&Display, false);

  becomes:

EditMenu ColorMenu(&Display);

Otherwise.... brilliant!. Thanks ,

Connal
