### ISSUE TITLE
Menu Exit

### ISSUE THREAD

**Issue by ConnalM** [KrisKasprzak/Adafruit_ST7735_Menu#2]
Hi,

Sorry to bother you again. I'm struggling with a niggling little problem, which I hope you can help me with.

I have set up a button that, when pressed for two seconds, calls ProcessMainMenu. When I exit out of the menu, it goes back to the previous screen, as required. However, if I then go back in to ProcessMainMenu, I'm immediately kicked out again.

This appears (to me) to be because the currentID/cr is set to 0, when it exited the menu the previous time. Setting the MainMenuOption to 1 has no effect , as it is soon overwritten by the line:

MainMenuOption = MainMenu.selectRow();

which is currentID/cr = 0

if I change MainMenuOption or set currentID/cr to 1, then I never get out of the menu. I'm sure there must be a simple solution that I am missing but I've spent quite a long time on it now, so I thought I'd ask the expert!

Thanks.

Connal

**Comment by KrisKasprzak** [comment]
can you post some code?

**Comment by ConnalM** [comment]
Sure.

This is the code that calls ProcessMainMenu:

void longclick()
{
    longClickPressed = !longClickPressed;  
    if (longClickPressed)
    {
      MainMenuOption = 1;  
      ProcessMainMenu();
    }
    if (!longClickPressed)
    {
      EEPROM.write(0,sensor_distance);
      write_to_Display();
    }
}

"write_to_Display" is a screen showing the main screen of information.

ProcessMainMenu is pretty much as your wrote it:

void allMenuSetup(){
  MainMenu.init(MENU_TEXT, MENU_BACKGROUND, MENU_HIGHLIGHTTEXT, MENU_HIGHLIGHT, 40, 2, "Main Menu", FONT_SMALL, FONT_SMALL);
  MenuOption1 = MainMenu.add565("Settings", epd_bitmap_put, 32, 32);
  MenuOption2 = MainMenu.add565("Calibration", epd_bitmap_Temp2, 32, 32);

  MainMenu.setTitleColors(TITLE_TEXT, TITLE_BACK);
  MainMenu.setTitleBarSize(0, 0, 160, 30);
  MainMenu.setTitleTextMargins(25, 20);
  MainMenu.setIconMargins(0, 0);
  MainMenu.setMenuBarMargins(0, 160, 0, 4);
  MainMenu.setItemColors(MENU_DISABLE, MENU_HIGHBORDER);
  MainMenu.setItemTextMargins(10, 20, 5);

  SettingsMenu.init(MENU_TEXT, MENU_BACKGROUND, MENU_HIGHLIGHTTEXT, MENU_HIGHLIGHT, MENU_SELECTTEXT,    MENU_SELECT,   DATA_COLUMN, 30,           3,                "Settings Menu",  FONT_SMALL, FONT_SMALL);

  //                             addNI(ItemText,        InitalDisplayData,  LowLimit, HighLimit,                                    Increment,  DecimalPlaces,  ItemMenuText);
  SettingsOption1 = SettingsMenu.addNI("Sensr Sep mm",  sensor_distance,    0,        300,                                          10,         0,              NULL);
  SettingsOption2 = SettingsMenu.addNI("Track Dis mm",  track_distance,     10,       100,                                          1,          0,              NULL);
  SettingsOption3 = SettingsMenu.addNI("Dis Var+/-mm",  distance_allowance, 10,       100,                                          1,          0,              NULL);
  SettingsOption3 = SettingsMenu.addNI("Units",         units,              0,        1,                                            1,          0,              UnitItems);
  SettingsOption5 = SettingsMenu.addNI("Gauge",         GaugeVal,           0,        sizeof(GaugeItems) / sizeof(GaugeItems[0]),   1,          0,              GaugeItems);


  SettingsMenu.setTitleColors(TITLE_TEXT, TITLE_BACK);
  SettingsMenu.setTitleBarSize(0, 0, 160, 25);
  SettingsMenu.setTitleTextMargins(30, 16);
  SettingsMenu.setIconMargins(0, 0);
  SettingsMenu.setItemTextMargins(1, 20, 5);
  SettingsMenu.setMenuBarMargins(0, 160, 0, 4);
  SettingsMenu.setItemColors(MENU_DISABLE, MENU_HIGHBORDER, MENU_SELECTBORDER);

  CalibrateMenu.init(MENU_TEXT, MENU_BACKGROUND, MENU_HIGHLIGHTTEXT, MENU_HIGHLIGHT, MENU_SELECTTEXT, MENU_SELECT,
                    DATA_COLUMN, 30, 3, "Calibrate Menu", FONT_SMALL, FONT_SMALL);
  CalibrateOption1 = CalibrateMenu.addNI("Left", 0, 0, 63, 1, 0);
  CalibrateOption2 = CalibrateMenu.addNI("Right", 0, 0, 255, 1, 0);
  CalibrateMenu.setTitleBarSize(0, 0, 160, 25);
  CalibrateMenu.setTitleTextMargins(30, 16);
  CalibrateMenu.setItemTextMargins(0, 20, 1);
  CalibrateMenu.setMenuBarMargins(2, 160, 0, 4);
  CalibrateMenu.setItemColors(MENU_DISABLE, MENU_HIGHBORDER, MENU_SELECTBORDER);
  CalibrateMenu.setTitleColors(TITLE_TEXT, TITLE_BACK);
  CalibrateMenu.setIncrementDelay(150);
}


void ProcessMainMenu() {
  MainMenuOption = 1;
  Display.fillScreen(MENU_BACKGROUND);
  MainMenu.draw();
  while (MainMenuOption != 0) {
    Position = encoder.getCount();
    if ((Position - oldPosition) > 0) {
      delay(DEBOUNCE);
      while (oldPosition != Position) {
        oldPosition = Position;
        Position = encoder.getCount();
      }
      MainMenu.MoveUp();
    }
    if ((Position - oldPosition) < 0) {
      delay(DEBOUNCE);
      while (oldPosition != Position) {
        oldPosition = Position;
        Position = encoder.getCount();
      }
      MainMenu.MoveDown();
    }
    if (digitalRead(PIN_SW) == LOW) {
      while (digitalRead(PIN_SW) == LOW) {
        delay(DEBOUNCE);
      }
      MainMenuOption = MainMenu.selectRow();
      if (MainMenuOption == MenuOption1) {
        ProcessSettingsMenu();
        Display.fillScreen(MENU_BACKGROUND);
        MainMenu.draw();
      }
      if (MainMenuOption == MenuOption2) {
        ProcessCalibrateMenu();
        Display.fillScreen(MENU_BACKGROUND);
        MainMenu.draw();
      }
    }
  }
  longClickPressed = !longClickPressed;
  return;
}

**Comment by ConnalM** [comment]
`void ProcessMainMenu() {
  MainMenuOption = 1;
  Display.fillScreen(MENU_BACKGROUND);
  MainMenu.draw();
  while (MainMenuOption != 0) {
    Position = encoder.getCount();
    if ((Position - oldPosition) > 0) {
      delay(DEBOUNCE);
      while (oldPosition != Position) {
        oldPosition = Position;
        Position = encoder.getCount();
      }
      MainMenu.MoveUp();
    }
    if ((Position - oldPosition) < 0) {
      delay(DEBOUNCE);
      while (oldPosition != Position) {
        oldPosition = Position;
        Position = encoder.getCount();
      }
      MainMenu.MoveDown();
    }
    if (digitalRead(PIN_SW) == LOW) {
      while (digitalRead(PIN_SW) == LOW) {
        delay(DEBOUNCE);
      }
      MainMenuOption = MainMenu.selectRow();
      if (MainMenuOption == MenuOption1) {
        ProcessSettingsMenu();
        Display.fillScreen(MENU_BACKGROUND);
        MainMenu.draw();
      }
      if (MainMenuOption == MenuOption2) {
        ProcessCalibrateMenu();
        Display.fillScreen(MENU_BACKGROUND);
        MainMenu.draw();
      }
    }
  }
  longClickPressed = !longClickPressed;
  return;
}`

**Comment by ConnalM** [comment]
Sure.

This is the routine that calls ProcessMainMenu.

void longclick()
{
    longClickPressed = !longClickPressed;  
    if (longClickPressed)
    {
      MainMenuOption = 1;  
      ProcessMainMenu();
    }
    if (!longClickPressed)
      EEPROM.write(0,sensor_distance);
      write_to_Display();
    }
}

write_to_Display is the main screen, from which the menu is called.

ProcessMainMenu is pretty much as you wrote it:

void ProcessMainMenu() {
  MainMenuOption = 1;
  Display.fillScreen(MENU_BACKGROUND);
  MainMenu.draw();
  while (MainMenuOption != 0) {
   Position = encoder.getCount();
    if ((Position - oldPosition) > 0) {
      delay(DEBOUNCE);
      while (oldPosition != Position) {
        oldPosition = Position;
        Position = encoder.getCount();
      }
      MainMenu.MoveUp();
    }
    if ((Position - oldPosition) < 0) {
      delay(DEBOUNCE);
      while (oldPosition != Position) {
        oldPosition = Position;
        Position = encoder.getCount();
      }
      MainMenu.MoveDown();
    }
    if (digitalRead(PIN_SW) == LOW) {
       while (digitalRead(PIN_SW) == LOW) {
        delay(DEBOUNCE);
      }
      MainMenuOption = MainMenu.selectRow();
      if (MainMenuOption == MenuOption1) {
        ProcessSettingsMenu();
        Display.fillScreen(MENU_BACKGROUND);
        MainMenu.draw();
      }
      if (MainMenuOption == MenuOption2) {
        ProcessCalibrateMenu();
        Display.fillScreen(MENU_BACKGROUND);
        MainMenu.draw();
      }
    }
  }
  longClickPressed = !longClickPressed;
  
  return;
}

Thanks

**Comment by KrisKasprzak** [comment]
I'm not sure how you are trapping a 2 second button press but if you not debouncing it properly, it will look pressed for the next function.
void loop() {
  // add this to global object creation  // elapsedMillis Update;  if (Update > 1000) {
    Update = 0;
    int Bits = analogRead(A5);    float Volts = Bits * 3.3 / 1024;
    Display.fillRect(50, 100, 150, 40, MENU_BACKGROUND);    Display.setFont(Arial_24_Bold);    Display.setTextColor(0, 255);    Display.setCursor(50, 100);
    Display.print(Volts, 3);    //Serial.println(Volts);    Serial.println(digitalRead(SE_PIN));
    // your button press code goes here    // my    if (digitalRead(SE_PIN) == LOW) {      Serial.println(digitalRead(SE_PIN));      // debounce the button press      unsigned long start = millis();      while (digitalRead(SE_PIN) == LOW) {        delay(DEBOUNCE);        if ((millis() - start) > 2000) {          break;        }      }      if ((millis() - start) > 2000) {        ProcessMainMenu();        Display.fillScreen(MENU_BACKGROUND);        // debounce button coming out of menu code        while (digitalRead(SE_PIN) == LOW) {          delay(DEBOUNCE);        }      }    }  }}
// inside ProcessMainMenu() you must debounce (or wait until button goes unpressedvoid ProcessMainMenu() {
  // set an inital flag that will be used to store what menu item the user exited on  int MainMenuOption = 1;
  // blank out the screen  Display.fillScreen(MENU_BACKGROUND);
//////////////////////////////////////////////////////////////////////////////////
  // make sure button is not pressed otherwise it will be mistaken for a menu exit press    // SE_PIN is the digitalRead pin for your button
  while (digitalRead(SE_PIN) == LOW) {    delay(DEBOUNCE);  }

//////////////////////////////////////////////////////////

Kris ***@***.***
 

    On Tuesday, March 21, 2023 at 04:47:27 AM CDT, ConnalM ***@***.***> wrote:  
 
 


Sure.

This is the routine that calls ProcessMainMenu.

void longclick()
{
longClickPressed = !longClickPressed;
if (longClickPressed)
{
MainMenuOption = 1;
ProcessMainMenu();
}
if (!longClickPressed)
EEPROM.write(0,sensor_distance);
write_to_Display();
}
}

write_to_Display is the main screen, from which the menu is called.

ProcessMainMenu is pretty much as you wrote it:

void ProcessMainMenu() {
MainMenuOption = 1;
Display.fillScreen(MENU_BACKGROUND);
MainMenu.draw();
while (MainMenuOption != 0) {
Position = encoder.getCount();
if ((Position - oldPosition) > 0) {
delay(DEBOUNCE);
while (oldPosition != Position) {
oldPosition = Position;
Position = encoder.getCount();
}
MainMenu.MoveUp();
}
if ((Position - oldPosition) < 0) {
delay(DEBOUNCE);
while (oldPosition != Position) {
oldPosition = Position;
Position = encoder.getCount();
}
MainMenu.MoveDown();
}
if (digitalRead(PIN_SW) == LOW) {
while (digitalRead(PIN_SW) == LOW) {
delay(DEBOUNCE);
}
MainMenuOption = MainMenu.selectRow();
if (MainMenuOption == MenuOption1) {
ProcessSettingsMenu();
Display.fillScreen(MENU_BACKGROUND);
MainMenu.draw();
}
if (MainMenuOption == MenuOption2) {
ProcessCalibrateMenu();
Display.fillScreen(MENU_BACKGROUND);
MainMenu.draw();
}
}
}
longClickPressed = !longClickPressed;

return;
}

Thanks

**Comment by ConnalM** [comment]
I'm not at home at the moment, so I can't give you details but there is a library for button clicks (OneButton?). It recognises a long press, 2 secs I think, and calls the routine.

The long press and the menu works the first time but the second time, it pops up the menu and then comes back out.

You are right that the menu is seeing the long press as a button press if i press for too long. So, first time it goes in to a submenu and the second time, because the Sr = exit, it comes straight back out.

Not sure if your code addresses this?

Thanks 

Connal

**Comment by KrisKasprzak** [comment]
I can't duplicate your issue so I'm not sure what can be changed. The example i replied with has a long press event that launches the menu. It can be repeated at will. However if I don't have code to wait until the button was unpressed, the menu would exit immediately.
Maybe try menu.init() before menu.draw().
If you can post a fully working (or failing) example, i'll debug it.


Thanks,
Kris ***@***.***
 

    On Tuesday, March 21, 2023 at 10:18:20 AM CDT, ConnalM ***@***.***> wrote:  
 
 


I'm not at home at the moment, so I can't give you details but there is a library for button clicks (OneButton?). It recognises a long press, 2 secs I think, and calls the routine.

The long press and the menu works the first time but the second time, it pops up the menu and then comes back out.

You are right that the menu is seeing the long press as a button press if i press for too long. So, first time it goes in to a submenu and the second time, because the Sr = exit, it comes straight back out.

Not sure if your code addresses this?

Thanks

Connal

**Comment by ConnalM** [comment]
Thanks. I'll post you the code soon,probably tomorrow now

Connal

**Comment by KrisKasprzak** [comment]
if you want to keep your code private you can send it to

**Comment by KrisKasprzak** [comment]
1. Mandatory
As I thought, you must handle the button press state and wait until the button is un pressed before proceeding. The button library while does have a long press, but it will not wait until the button is un pressed. This caused the library to "think" you were pressing on the exit row. Basically enter a while loop and don't exit until the button state is HIGH

just after the MainMenu.draw() method. I personally like drawing the menu first the wait until the button is un pressed which acts as a prompt for the user to release the button. Something like this:

  while (digitalRead(PIN_SW) == LOW){
    delay(10);
  }

2. Optional. If you want to always have a certain row highlighted upon entering the menu code, I have added a method to set the starting row in the menu so you can always see a desired row ready for select. You will need to get the latest library and add this code just before MainMenu.draw():
MainMenu.setInitialItem(MenuOption1);

**Comment by ConnalM** [comment]
Me again...

How feasible would it be to have your menu with two entries but, instead of
a vertical list, have the entries side by side. Also, would it be possible
to have a 'live feed' from a couple of sensors?

I have to ranging sensors that are arranged left and right. The range is
changed by selecting one of the sensors and rotating the knob (similar to a
normal menu entry) but I want the new range reading to be displayed above
the menu entry setting. I can do this but it would be great to have the
same 'look and feel' as your menu.

Please note, I'm not asking you to do this but just to give me a feel for
if it is worth trying to do.

Thanks,

Connal

**Comment by KrisKasprzak** [comment]
Unless I’m not following, you should be able to do this right now. Create two menu objects, but just narrow the width of the menus to half screen. display one menu on the left side of the screen the other menu on the right side of the screen, you could dynamically populate the list With sensor values. There is a constant in the . H file that limits the amount of menu entries you can add so you have to bump that up then just use the  add method to populate the lists and the dot ad method could be done anywhere in your code . Thanks.Kris KasprzakOn Mar 30, 2023, at 4:40 AM, ConnalM ***@***.***> wrote:﻿
Me again...

How feasible would it be to have your menu with two entries but, instead of
a vertical list, have the entries side by side. Also, would it be possible
to have a 'live feed' from a couple of sensors?

I have to ranging sensors that are arranged left and right. The range is
changed by selecting one of the sensors and rotating the knob (similar to a
normal menu entry) but I want the new range reading to be displayed above
the menu entry setting. I can do this but it would be great to have the
same 'look and feel' as your menu.

Please note, I'm not asking you to do this but just to give me a feel for
if it is worth trying to do.

Thanks,

Connal

**Comment by ConnalM** [comment]
Kinda with you.... however...

1) Can the left and right menus be on the same screen? I can't see a way to
do that.
2) The left menu is kinda ok but right is completely screwed
3) the exit button now doesn't work on the calibration screens (still works
on the other menu screens.
4) and I didn't understand why I would need to bump up the number of  menu
entries or which lists you were talkign about populating.("There is a
constant in the . H file that limits the amount of menu entries you can add
so you have to bump that up then just use the  add method to populate the
lists and the dot ad method could be done anywhere in your code .")
I've attached the code, if you are feeling generous...

Thanks,

Connal

[image: 20230330_185436.jpg]
[image: 20230330_185317.jpg]

**Comment by ConnalM** [comment]
OK

I have made some progress -

I have made a slight change to your menu.cpp.

From:

void EditMenu::setMenuBarMargins(uint16_t LeftMargin, uint16_t Width,
uint16_t BorderRadius, uint16_t BorderThickness) {
  isx = LeftMargin;  // pixels to offset text in menu bar
  irw = Width - isx;  // pixels to offset text in menu bar
  radius = BorderRadius;
  thick = BorderThickness;

to

void EditMenu::setMenuBarMargins(uint16_t LeftMargin, uint16_t Width,
uint16_t BorderRadius, uint16_t BorderThickness) {
  isx = LeftMargin;  // pixels to offset text in menu bar
  irw = Width;*// - isx;*  // pixels to offset text in menu bar
  radius = BorderRadius;
  thick = BorderThickness;

This is because the margin was being taken off the width, as well as
setting the indent; so I could never get the menu bar margin to sit from 80
to 160.

Most of the other issues were down to cut and paste errors or me not
understanding how your screens are set up.

So, I think the only thing remaining is putting both menus on one screen,
which may not be possible. I'll keep playing about with it and let you know
if I have any inspiration.

Thanks,

Connal
